---
title: "Tutorial to train, evaluate, and project Species Distribution Models for benthic organisms using the 'biomod2' package"
author: "Damiano Baldan"
date: "`r Sys.Date()`"
output: rmdformats::downcute
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
---

# Content

This document is a step-by-step tutorial to fit Species Distribution Models (SDMs) for benthic organisms using the 'biomod2' package. The main steps of the tutorial will describe how to (1) pre-process the environmental data, (2) fit SDMs, (3) evaluate SDMs, and (4) project SDMs to generate distribution maps.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Introduction

This document is a step-by-step guide to create an `igraph` object starting from commonly available geodata. Here, an example is provided using data for the Ebro river (Spain), based on widely available geodata from HydroSHEDS and public repositories from the Hydrographic Confederation of the Ebro river [`CHE`](http://iber.chebro.es/geoportal/).

The source code used to generate this tutorial is available on [github](https://github.com/damianobaldan/riverconn_tutorial) in the file `tutorial_network_creation.Rmd`; additional functions used in the tutorial are stored in the file `functions_network_creation.R`.

After this tutorial is completed, the resulting  `igraph` object is meant to be used as input to functions to assess riverscape fragmentation. The `riverconn` package (available on [CRAN](https://cran.r-project.org/package=riverconn) and on [github](https://github.com/damianobaldan/riverconn)) allows for the calculation of many fragmentation/connectivity indices.  Most graph theory-based indices to asses fragmentation and connectivity of rivers (see Jumani et al., 2020 for a review) conceptualize the riverscape as a graph where vertices (nodes) represent reaches, i.e. distintictly separated river sections; while edges (links) represent splitting objects, such as confluences (where two reaches join), barriers (items that disrupt the longitudial connectivity of the river), or habitat patches boundaries (borders between sections of the river with relatively uniform habitat conditions). This tutorial focuses on barriers (dams), but in principle other fragmentation items can be dealt with similarly.

The [`igraph`](https://cran.r-project.org/web/packages/igraph/index.html) package implements routines for graphs and network analysis. It can handle large graphs very well and provides functions for generating random and regular graphs, graph visualization, centrality methods and much more. The packages allows for easy [construction](https://igraph.org/r/doc/aaa-igraph-package.html) of `igraph` objects based on symbolic description of edges and vertices, edges and vertices lists, or adjacency matrices. The book [Statistical Analysis of Network Data with R by Kolaczyk and Csardi (2014)](https://link.springer.com/book/10.1007%2F978-3-030-44129-6) offers a comprehensive tutorial on the possibilities offered by the `igraph` package, including network data manipulation and visualization, descriptive analysis of network graphs, mathematical and statistical modeling of graphs, and network topology inference.

# 1.1 Packages needed

























